### PR TITLE
Please review and approve changes made in the testfile.

### PR DESCRIPTION
**Pull request by MasterYiTheSamurai**

### CODE REVIEW

**Comment by ChaitanyaYeole02** [comment]
@MasterYiTheSamurai , I am confused why did you change the TestGroup4. As the timestamp Rollbacks to 2021-07-01T12:10:00 and Update2.txt and Update1Copy.txt happens at 2021-07-01T12:20:00 and 2021-07-01T12:15:00 respectively.

@PaulLockett Please clarify.

**Comment by ChaitanyaYeole02** [comment]
You changed the TestGroup4, which I think was not needed.

**Comment by Silent-Zebra** [comment]
Agreed with [ChaitanyaYeole02](https://github.com/ChaitanyaYeole02), I think TestGroup4 is wrong now, and it should be the old version results before the latest commit, as once we've rolled back the file system, we no longer have the copies that were made after the timestamp that we roll back to:

self.assertEqual(output, ["uploaded at Initial.txt",
                                  "uploaded at Update1.txt",
                                  "got at Initial.txt",
                                  "copied at Update1.txt to Update1Copy.txt",
                                  "uploaded at Update2.txt",
                                  "rollback to 2021-07-01T12:10:00",
                                  "got at Update1.txt", "got at Initial.txt", "found at [Update1.txt]", "file not found"])

**Comment by PaulLockett** [comment]
@Silent-Zebra or @ChaitanyaYeole02 drop a pr with the correct version of the test file please. I will review that.

**Pull request merged**
